name: controle_alunos_musica_ft
description: Controle Alunos MÃºsica FT.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: 2.0.3+1
  mobx: 2.0.7+5
  flutter_mobx: 2.0.6+1
  url_launcher: 6.1.5
  fluttertoast: 8.0.9
  intl: ^0.18.1
  path_provider: ^2.0.11
  open_file: ^3.2.1
  font_awesome_flutter: ^10.7.0
  permission_handler: ^11.0.1
  android_intent_plus: ^5.2.2

  cupertino_icons: ^1.0.2
  pdf: ^3.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  mobx_codegen: 2.0.7
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

dependency_overrides:
  watcher: ^1.1.0

flutter_icons:
  image_path: assets/images/app-icon.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/